name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name ImageWatermarkProcessor img2mask.py

      - name: Verify dist directory
        shell: pwsh
        run: Get-ChildItem -Path dist -Recurse

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageWatermarkProcessor-Windows
          path: dist/ImageWatermarkProcessor.exe

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::release_$(date +'%Y.%m.%d_%H-%M')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          release_name: Release ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/ImageWatermarkProcessor.exe
          asset_name: ImageWatermarkProcessor.exe
          asset_content_type: application/octet-stream
